name: Terraform CI/CD
on: 
  pull_request: 
   branches: 
     - devlop
     - main

  push: 
   branches: 
     - main 

permissions: 
  id-token: write
  contents: read
defaults:
  run:
    working-directory: ./

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_USE_OIDC: true

jobs:
  terraform_scan:
    name: Terraform scan

    runs-on: ubuntu-latest
    defaults:
      run:
          working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
  
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
  
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6.3.0
  
      - name: Run TFlint
        run: tflint --recursive
        continue-on-error: true
  
  
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        continue-on-error: true


  terraform_init_plan:
    name: Terraform Init & Plan
    needs: terraform_scan
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan




      
